crud-alumno
tomas0011/Clase5EP-Unahur pull request #17
Opened 2022-10-08 18:38 UTC by LautaroRiofrio

2022-10-11 21:15 UTC, tomas0011 approved these changes

2022-10-11 21:15 UTC, tomas0011 commented
Faltan las relaciones de alumno con el resto de tablas

2022-10-12 00:20 UTC, nachofazah approved these changes

2022-10-19 00:05 UTC, tomas0011 requested changes

2022-10-19 00:05 UTC, tomas0011 commented on api/migrations/1-create-comision-alumno.js
> +};
Ultima linea vacia en el documento

2022-10-19 00:05 UTC, tomas0011 commented on api/models/comisionalumno.js
> +};
Ultima linea vacia en el documento

2022-10-19 00:06 UTC, LautaroRiofrio commented
https://drive.google.com/file/d/10X1T5j3ZPTzhInMUVeXtd9NRYdoPWoEA/view?usp=sharing

2022-10-19 02:52 UTC, tomas0011 approved these changes

2022-10-19 02:53 UTC, merged